### PR TITLE
Add Travis CI configuration file

### PR DESCRIPTION
**Pull request by bluca**
Hi,

This commit adds a simple Travis CI configuration. It supports the new container-based infrastructure.

In case you are interested and think this can be useful to have, you'll neel to enable the repository on: https://travis-ci.org/NVIDIA

This is an example run: https://travis-ci.org/bluca/libglvnd

### CODE REVIEW

**Comment by evelikov** [comment]
@bluca in theory one can setup an X instance see [1] although I'm not sure how useful would that be here. That said, I love when people use CI. Although please use
` ./autogen.sh && make -j2 distcheck 
`
It does all a lot more than a simple make && make install

[1] https://github.com/anholt/libepoxy/blob/master/.travis.yml

**Comment by bluca** [comment]
@evelikov - thanks for the suggestion, it seems to work perfectly, even in the docker container build! The tests work and pass, awesome!

**Comment by bluca** [comment]
Updated to run distcheck as suggested by @evelikov - as usual comments get lost as they are associated with individual commits.

**Comment by kbrenneman** [comment]
One thing we'll need to watch out for is that I don't think Xvfb supports the GLX extension.

libGLX.so should be able to run anyway, though, at least enough to run the tests.

**Comment by aaronp24** [comment]
I wonder if one of the other competing products to Travis CI (maybe https://github.com/Strider-CD/strider?) would allow running a real X server somewhere.  It's a bit of a shame to clutter the repository with artifacts for the GitHub fad-of-the-day, but if no one else minds, I don't have any objection and this does seem useful.

**Comment by aaronp24** [comment]
Never mind, I didn't realize Travis CI was open source too.  So that would just be a matter of learning how to configure a custom instance somewhere in order to run on real hardware.

**Comment by bluca** [comment]
Hi,

I picked Travis just because I'm familiar with it and because the NVIDIA Github Org already uses it for 2 projects:
https://travis-ci.org/NVIDIA/DIGITS
https://travis-ci.org/NVIDIA/caffe

So I thought it would be easier for you guys to use it here too. No strong preference, so if there's an alternative you prefer I can have a look :-)

The following tests successfully PASS with the current config, the rest are SKIPPED (so run is successful):

testglxgetprocaddress.sh
testglxmcbasic.sh
testglxmcloop.sh
testglxmcthreads.sh
testglxmclate.sh
testglxmcoldlink.sh
testglxgetclientstr.sh
testglxqueryversion.sh
testpatchentrypoints.sh

https://travis-ci.org/bluca/libglvnd

**Comment by tfogal** [comment]
Maybe testing could be done via EGL, to remove the X dependency?

My (likely faulty) understanding is that basic GLX transport works fine with Xvfb, but non-ancient OGL breaks.  IIRC the issue is that Xvfb uses an indirect context and indirect contexts can't do shaders etc.

**Comment by kbrenneman** [comment]
> Maybe testing could be done via EGL, to remove the X dependency?

EGL isn't implemented yet, but once it is, most of the libGLdispatch-layer changes can go through EGL.

Testing libGLX itself would still need a server, though.

> My (likely faulty) understanding is that basic GLX transport works fine with Xvfb, but non-ancient OGL breaks. IIRC the issue is that Xvfb uses an indirect context and indirect contexts can't do shaders etc.

libGLX by itself depends on the GLX server extension in order to report errors, since it needs to know the base error value and the opcode for it. In addition, libGLX's implementation of glXQueryVersion handles sending the GLX request on its own instead of handing it off to a vendor library.

libGLX should mostly work without the server extension, though. It'll skip reporting errors, and glXQueryVersion and glXQueryExtension will fail, but everything else should work.

I get different results for whether GLX is supported on two different systems, though, and I haven't figured out what the difference is.

**Comment by bluca** [comment]
@kbrenneman - ping :-)

Anything you guys would like me to do?

**Comment by aaronp24** [comment]
There was some talk about moving libglvnd to git.freedesktop.org and making it an official Freedesktop project, so we should probably decide on that first.

**Comment by aaronp24** [comment]
Eric Anholt is making a push to add Travis CI coverage to various X.Org projects, and moving their builds to Meson to make that more feasible. I don't think there's any pushback from X.Org to adding this kind of thing, so it's just up to @kbrenneman to decide whether to turn this on.

I started looking into using Meson to build libglvnd, but it has some limitations that make it not so great for that. It's *way* faster than autoconf / automake, though.

**Comment by kbrenneman** [comment]
We've migrated the repository over to GitLab, so this is now tracked at https://gitlab.freedesktop.org/glvnd/libglvnd/merge_requests/55.

**Pull request closed without merging**
