### PR TITLE
Remove -Wno-misleading-indentation

### PR DESCRIPTION
**Pull request by aaronp24**
This option is not recognized by clang, so it produces an error when configured
with

  CC=clang ./configure

  error: unknown warning option '-Wno-misleading-indentation'; did you mean '-Wno-missing-declarations'? [-Werror,-Wunknown-warning-option]

This flag is only needed for cJSON.c. Deobfuscate that file just enough to
eliminate the misleading indentation warnings, then remove the warning flag from
Makefile.am.

### CODE REVIEW

**Comment by kbrenneman** [comment]
Out of curiosity, does the upstream version of cJSON have the same problem? The one in glvnd is a little out of date, updating the whole library might not be a bad idea.

**Comment by aaronp24** [comment]
It doesn't look like it does. The whole thing was completely revamped a while back. I'll add a commit to update to the latest release.

**Comment by aaronp24** [comment]
I verified that this passes "make distcheck" and that the installed library can look up /usr/share/glvnd/egl_vendor.d/10_nvidia.json and find libEGL_nvidia.so.0 from it.

**Comment by kbrenneman** [comment]
Cool. I just finished running the unit tests over here, too. Looks good to me.

**Pull request merged**
