### PR TITLE
Build cleanups round2

### PR DESCRIPTION
**Pull request by evelikov**
Another round of configure.ac cleanups which removes a handful of the unneeded type/function/header checks.

Note this is based against the earlier series, although (barring the trivial conflicts) can be applied independently

### CODE REVIEW

**Comment by kbrenneman** [comment]
While it seems to finish okay, running autogen.sh gives me a boatload of warnings now.

**Comment by kbrenneman** [comment]
Ah, now that I look closer, I guess those warnings were all there before, but the old autogen.sh didn't print them out by default.

**Comment by evelikov** [comment]
Indeed. These series should even nuke some of the issues/warnings ;-)

As github PR are pain in the ass let me know if things are ok as is or you'd like me to respin things in a particular way. Alternatively are you guys interested in having the whole thing setup on fd.o with proper mailing list, perhaps even with bugzilla/phabricator/patchwork instance ? The latter might take a while to setup although the former could be done within a day.

**Comment by aaronp24** [comment]
There are a few build artifacts on my system that aren't in your updated .gitignore.  After autogen.sh:
```
git status -s
?? bin/
```
After ./configure:
```
$ git status -s
?? bin/
?? stamp-h1
```
After building:
```
$ git status -s
?? bin/
?? src/GL/g_glapi_mapi_gl_tmp.h
?? src/GL/g_libglglxwrapper.c
?? src/GLESv1/g_glapi_mapi_glesv1_tmp.h
?? src/GLESv1/g_glesv1_exports.sym
?? src/GLESv2/g_glapi_mapi_glesv2_tmp.h
?? src/GLESv2/g_glesv2_exports.sym
?? src/GLX/g_libglxnoop.c
?? src/GLdispatch/vnd-glapi/g_glapi_inittable.c
?? src/GLdispatch/vnd-glapi/glapi_mapi_tmp.h
?? src/GLdispatch/vnd-glapi/glapitable.h
?? src/OpenGL/g_glapi_mapi_opengl_tmp.h
?? src/OpenGL/g_opengl_exports.sym
?? stamp-h1
```

**Comment by evelikov** [comment]
Looks like I'm from the few that do out of tree builds :-)

Fwiw 'make check' adds a few more files - then again not sure how the original autogen.sh was working around these. Patch coming in a second.

**Comment by evelikov** [comment]
A couple of patches on top - one adds all the missing files and a second to slim down the top level .gitignore.

**Comment by evelikov** [comment]
Updated pull request to address the spelling/grammar suggestions.

Note: I will temporaryly close the other PR that depend on this one, as things are bound to get messy.

**Pull request merged**
