### PR TITLE
GLX: implement __glXGLLoadGLXFunction fast path

### PR DESCRIPTION
**Pull request by evelikov**
Trivial optimisation I've stumbled upon while going through.
Add fast path for the entry points initialised in libGLX' constructor leading to 10-40% improvement.

### CODE REVIEW

**Comment by kbrenneman** [comment]
For what it's worth, it's possible that the core GLX functions to already be cached when __glXWrapperInit is called, if libGLX.so was loaded and used, and then libGL.so was loaded later with dlopen.

I'd say that it's really, really unlikely for that to happen, so optimizing based on that assumption makes sense, as long as it doesn't break if that assumption doesn't hold.

In this case, both cacheProcAddress and __glXGetCachedProcAddress should be thread-safe and idempotent, so I think this change should be all right.

@evelikov - Do you think it would make sense to just remove the call to cacheProcAddress from loadABIGLXFunction? That would further reduce the time for __glXWrapperInit, and probably by quite a bit, since __glXGetGLXDispatchAddress would hit its early-out case.

If we did that, then the first call to glXGetProcAddress from the app for one of those functions wouldn't be cached, but I'd also expect those calls to be pretty infrequent, and I doubt any app would expect glXGetProcAddress to be especially fast.

**Comment by evelikov** [comment]
Bth, I was split about removing the cacheProcAddress() call. But in all fairness it can go and give us a consistent 30-45% of the original runtime.

The potential glXGetProcAddress slowness can be remedied very easily with a local dispatch for the said symbols. But that's somewhat orthogonal.

Updated patch coming in a minute.

**Comment by evelikov** [comment]
Updated patch has been around for 1 week. Any comments/suggestions?

**Comment by kbrenneman** [comment]
I thought you were going to add a follow-up change to remove the cacheProcAddress() call, so I was waiting on that before merging.

**Comment by kbrenneman** [comment]
Now that I think about it, the functions initialized in __glXWrapperInit are the core GLX functions, which means they're all defined in libGLX.so, and the set of those functions isn't going to change any time soon.

So, libGL.so could use a table to look those up instead of trying to look them up by name. That would let us remove __glXWrapperInit entirely.

**Comment by evelikov** [comment]
> I thought you were going to add a follow-up change to remove the cacheProcAddress() call, so I was waiting on that before merging.

The change requested is a fixup so I squashed it with the commit - as mentioned in the comment.
Either way - #127 sounds like a better solution, so let's close this.

**Pull request closed without merging**
