### PR TITLE
Small pkg-config, autotools and README.md fixes

### PR DESCRIPTION
**Pull request by bluca**
Hi,

Few tiny fixes:

- check for glproto in configure.ac, make check tests fail to build without it
- remove autogenerated sources and .pyc files on make clean
- document build dependencies in README

### CODE REVIEW

**Comment by bluca** [comment]
Dropped the pkg-config cflag commit following @kbrenneman comment

**Comment by evelikov** [comment]
@bluca out of curiosity - where can one see the dropped commit/comment ?

The first two patches look great, feel free to add
Reviewed-by: Emil Velikov <emil.velikov@collabora.com>

**Comment by bluca** [comment]
@evelikov - Unfortunately due to how the PR comments work, once a commit is removed the comments become invisible in the PR itself.

But you can still see them in my fork: https://github.com/bluca/libglvnd/commit/7bd2236f0ca5b9261054c2d9de4e60d6e4985e87#commitcomment-15653193

**Comment by evelikov** [comment]
> @evelikov - Unfortunately due to how the PR comments work, once a commit is removed the comments become invisible in the PR itself.
> But you can still see them in my fork: bluca@7bd2236#commitcomment-15653193

Have to love the github PR system :-P But seriously - thanks for the link. It all makes perfect sense.

**Comment by evelikov** [comment]
FTR it seems that libglvnd has imported an incomplete version of glproto in-tree. With the above series in place we can nuke them (have a pending patch)

**Comment by evelikov** [comment]
Bth I'm not sold on the rm -rf .pyc change, mostly because I've not seen it elsewhere. Then again my days of looking at debian's packaging are long gone :-\
@kbrenneman the series looks great imho. What's required to get it pulled ?

**Comment by kbrenneman** [comment]
Looks good to me.

**Comment by bluca** [comment]
Thanks!

**Pull request merged**
