### PR TITLE
configure and build cleanups et al

### PR DESCRIPTION
**Pull request by evelikov**
Hi all,

Here is a bunch of cleanups which I've accumulated. The only thing (somewhat) controversial is the replacement of the autogen.sh with a x.org/mesa one.

Comments and suggestions are welcome.
Emil

### CODE REVIEW

**Comment by kbrenneman** [comment]
Well, I wouldn't object to a shorter, simpler autogen.sh script as long as it works. The current script pre-dates when I started working on libglvnd, and I don't pretend to understand how it works.

But, it shouldn't run configure automatically. I almost always run configure in a separate directory, so running it the root of the source tree is a major annoyance.

**Comment by aaronp24** [comment]
I agree that it's annoying when autogen.sh runs configure automatically, but that seems to be the de facto standard -- it's unusual and surprising to me when one doesn't.  Maybe I just build X.Org packages more often than most people?

**Comment by evelikov** [comment]
One can avoid the configure execution by setting NOCONFIGURE, as defined here [1] - many/most X.org package honour it. Although the documents says "[autogen.sh] SHOULD NOT run ./configure", I'm leaning towards consistency with existing packages. Then again I won't feel too strong if it goes away :-)

[1] http://people.gnome.org/~walters/docs/build-api.txt

**Comment by kbrenneman** [comment]
I'd say either take out the configure call, or make it only run configure if you set a flag or an environment variable. The default behavior if you forget to set a flag should be the one that deposits the least amount of clutter in your source tree.

**Comment by evelikov** [comment]
> or make it only run configure if you set a flag or an environment variable

I'd rather not do that. Whereas to the removal of the configure call, I'll split that as a separate commit on top (once we get confirmation on the autoconf/python question)

**Comment by evelikov** [comment]
Closing this in favour of pull #70. It already includes this and a few extra changes/fixes.

**Pull request closed without merging**
